restructure ci file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -47,37 +47,35 @@ jobs:
     #      - 6379:6379
     #    options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
     steps:
-      - name: Install packages
-        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git pkg-config
-      
-      - name: Install Bundler
-        run: gem install bundler --user-install
-
-      - name: Update PATH for Bundler
-        run: echo "$HOME/.gem/ruby/3.2.0/bin" >> $GITHUB_PATH
-
-      - name: Debug bin directory
-        run: ls -l bin/ || echo "bin/ directory is missing"
-
-      - name: Ensure bin/ exists
-        run: |
-          bundle exec rails app:update:bin
-          chmod +x bin/rails
-
-      - name: Install dependencies
-        run: bundle install
-
-      - name: Set executable permissions for bin/rails
-        run: chmod +x ./bin/rails
-
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Install packages
+        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git pkg-config
 
       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
         with:
           ruby-version: .ruby-version
           bundler-cache: true
+      
+      - name: Install Bundler
+        run: gem install bundler --no-document
+
+      - name: Update PATH for Bundler
+        run: echo "$HOME/.gem/ruby/3.2.0/bin" >> $GITHUB_PATH
+
+      - name: Install dependencies
+        run: bundle install --jobs=4 --retry=3
+
+      - name: Debug bin directory
+        run: ls -l bin/ || echo "bin/ directory is missing"
+
+      - name: Ensure bin/ exists
+        run: bundle exec rails app:update:bin
+
+      - name: Set executable permissions for bin/rails
+        run: chmod +x ./bin/rails
 
       - name: Run tests
         env:
